name: Run Jest testing suite
on:
  workflow_dispatch:
  push:
    branches:
      - development
  pull_request:

env:
  NODE_ENV: 'test'

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Testing
        run: |
          yarn
          yarn test | tee ./coverage.txt && exit ${PIPESTATUS[0]}
      - name: Jest Coverage Comment
        # Ensures this step is run even on previous step failure (e.g. test failed)
        if: always()
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: coverage/coverage-summary.json
          junitxml-path: junit.xml
          junitxml-title: JUnit
          coverage-path: ./coverage.txt
